# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ufabccentral' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ufabccentral
  pod 'Amplitude-iOS', '~> 4.3.1'

  target 'ufabccentral-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ufabccentralTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
